project:
  type: book
  output-dir: docs

book:
  title: "Introduction to Data Science with Python"
  subtitle: "With Real-World Examples from Research, Business and Industry"
  author: "The GRAPH Courses"
  cover-image: cover.jpg
  favicon: logo.png
  repo-url: https://github.com/the-graph-courses/idap_book
  repo-branch: main
  repo-actions: [edit, issue]
  page-footer:
    left: |
      Book created by <a href="https://thegraphcourses.org/">The GRAPH Courses</a>
    right: |
      TEMPORARY For a PDF copy, please visit this <a href="https://raw.githubusercontent.com/the-graph-courses/idar_book/main/pdf/Introduction-to-Data-Analysis-with-R.pdf">page</a>.
  chapters:
    - index.qmd

    
    ## Use the below for HTML render. (Parts don't seem to work in HTML render)
    - part: "Foundations"
      chapters:
        - p_foundations_google_colab.qmd
        - p_foundations_coding_basics.qmd
        - p_foundations_functions_methods.qmd
        - p_foundations_data_structures.qmd
        - p_foundations_for_loops.qmd
        - p_foundations_installing_python.qmd
        - p_foundations_using_vscode.qmd
        - p_foundations_venv.qmd
        - p_foundations_quarto.qmd
    - part: "Data Visualization"
      chapters:
        - p_data_on_display_data_viz_types.qmd
        - p_data_on_display_univariate.qmd
        - p_data_on_display_multivariate.qmd
    - part: "Data Manipulation"
      chapters:
        - p_untangled_subset_columns.qmd
        - p_untangled_query_rows.qmd
        - p_untangled_assign.qmd
        - p_untangled_case_when.qmd
        - p_untangled_groupby_agg.qmd
        - p_untangled_other_grouped_operations.qmd
        - p_untangled_pivoting.qmd

    ## Use the below for PDF render
    # - p_foundations_google_colab.qmd
    # - p_foundations_coding_basics.qmd
    # - p_foundations_functions_methods.qmd
    # - p_foundations_data_structures.qmd
    # - p_foundations_for_loops.qmd
    # - p_data_on_display_data_viz_types.qmd
    # - p_data_on_display_univariate.qmd
    # - p_data_on_display_multivariate.qmd
    # - p_untangled_subset_columns.qmd
    # - p_untangled_query_rows.qmd
    # - p_untangled_assign.qmd
    # - p_untangled_case_when.qmd
    # - p_untangled_group_by_agg.qmd
    # - p_untangled_other_grouped_operations.qmd
    # - p_untangled_pivoting.qmd

resources:
  - CNAME

format:
  # PrettyPDF-pdf:
  #   keep-tex: true
  #   toc: true
  html:
    theme: 
      - cosmo
      # - custom.scss
    css: style.css

editor: source


